elanguage: php

php:
  - "7.2"

before_script:
  - cp .env.example .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

services:
  - mysql

script:
- vendor/bin/phpunit
